#!/bin/sh
## This is a rcS file for startup, net interface config 
if [ -e /bin/wpa_supplicant ] ; then
    ifconfig wlan0 up
    mkdir -p /var/run/wpa_supplicant
    [ -e /etc/wpa_supplicant.conf ] || /bin/wpa_supplicant -B -c/etc/wpa_supplicant.conf -iwlan0
fi