#! /bin/sh
# This is a minmal rcS file for target startup
# Make sure that /proc is mounted.
## Modify by liweijie for AUTOELEC platform @2020-1-11

# Mount device or filesystem listed in /etc/fstab.
/bin/mount -a

[ -e /proc/hikbase/bootts ] && /bin/echo kernel > /proc/hikbase/bootts
[ -e /proc/hikbase/bootts ] && /bin/echo rcS > /proc/hikbase/bootts

ifconfig lo 127.0.0.1 up

for initscript in /etc/rcS.d/S[0-9][0-9]*
do
     # Ignore dangling symlinks (if any).
     [ ! -f "$initscript" ] && continue

     [ -e /proc/hikbase/bootts ] && /bin/echo $(basename $initscript) > /proc/hikbase/bootts
	 # echo "$initscript start $(date)";
     case "$initscript" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $initscript
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $initscript start
	    ;;
    esac
     [ -e /proc/hikbase/bootts ] && /bin/echo $(basename $initscript) > /proc/hikbase/bootts
done

[ -e /proc/hikbase/bootts ] && /bin/echo rcS > /proc/hikbase/bootts

exit 0
